// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: nomad_botherer.proto

package grpcapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NomadBotherer_GetDiffs_FullMethodName        = "/nomad_botherer.v1.NomadBotherer/GetDiffs"
	NomadBotherer_GetSelectedJobs_FullMethodName = "/nomad_botherer.v1.NomadBotherer/GetSelectedJobs"
	NomadBotherer_GetStatus_FullMethodName       = "/nomad_botherer.v1.NomadBotherer/GetStatus"
	NomadBotherer_TriggerRefresh_FullMethodName  = "/nomad_botherer.v1.NomadBotherer/TriggerRefresh"
	NomadBotherer_GetVersion_FullMethodName      = "/nomad_botherer.v1.NomadBotherer/GetVersion"
)

// NomadBothererClient is the client API for NomadBotherer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NomadBotherer allows operators to query drift state and trigger refreshes.
type NomadBothererClient interface {
	// GetDiffs returns the current set of job diffs detected between git and Nomad.
	GetDiffs(ctx context.Context, in *GetDiffsRequest, opts ...grpc.CallOption) (*GetDiffsResponse, error)
	// GetSelectedJobs returns all jobs that matched the configured selection
	// criteria during the last check, together with the reason each was included.
	GetSelectedJobs(ctx context.Context, in *GetSelectedJobsRequest, opts ...grpc.CallOption) (*GetSelectedJobsResponse, error)
	// GetStatus returns git watcher status (last commit, last update time).
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// TriggerRefresh causes an immediate git pull and diff check.
	TriggerRefresh(ctx context.Context, in *TriggerRefreshRequest, opts ...grpc.CallOption) (*TriggerRefreshResponse, error)
	// GetVersion returns the server build version, commit hash, and build date.
	GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error)
}

type nomadBothererClient struct {
	cc grpc.ClientConnInterface
}

func NewNomadBothererClient(cc grpc.ClientConnInterface) NomadBothererClient {
	return &nomadBothererClient{cc}
}

func (c *nomadBothererClient) GetDiffs(ctx context.Context, in *GetDiffsRequest, opts ...grpc.CallOption) (*GetDiffsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDiffsResponse)
	err := c.cc.Invoke(ctx, NomadBotherer_GetDiffs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nomadBothererClient) GetSelectedJobs(ctx context.Context, in *GetSelectedJobsRequest, opts ...grpc.CallOption) (*GetSelectedJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSelectedJobsResponse)
	err := c.cc.Invoke(ctx, NomadBotherer_GetSelectedJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nomadBothererClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, NomadBotherer_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nomadBothererClient) TriggerRefresh(ctx context.Context, in *TriggerRefreshRequest, opts ...grpc.CallOption) (*TriggerRefreshResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerRefreshResponse)
	err := c.cc.Invoke(ctx, NomadBotherer_TriggerRefresh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nomadBothererClient) GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVersionResponse)
	err := c.cc.Invoke(ctx, NomadBotherer_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NomadBothererServer is the server API for NomadBotherer service.
// All implementations must embed UnimplementedNomadBothererServer
// for forward compatibility.
//
// NomadBotherer allows operators to query drift state and trigger refreshes.
type NomadBothererServer interface {
	// GetDiffs returns the current set of job diffs detected between git and Nomad.
	GetDiffs(context.Context, *GetDiffsRequest) (*GetDiffsResponse, error)
	// GetSelectedJobs returns all jobs that matched the configured selection
	// criteria during the last check, together with the reason each was included.
	GetSelectedJobs(context.Context, *GetSelectedJobsRequest) (*GetSelectedJobsResponse, error)
	// GetStatus returns git watcher status (last commit, last update time).
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// TriggerRefresh causes an immediate git pull and diff check.
	TriggerRefresh(context.Context, *TriggerRefreshRequest) (*TriggerRefreshResponse, error)
	// GetVersion returns the server build version, commit hash, and build date.
	GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error)
	mustEmbedUnimplementedNomadBothererServer()
}

// UnimplementedNomadBothererServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNomadBothererServer struct{}

func (UnimplementedNomadBothererServer) GetDiffs(context.Context, *GetDiffsRequest) (*GetDiffsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiffs not implemented")
}
func (UnimplementedNomadBothererServer) GetSelectedJobs(context.Context, *GetSelectedJobsRequest) (*GetSelectedJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSelectedJobs not implemented")
}
func (UnimplementedNomadBothererServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedNomadBothererServer) TriggerRefresh(context.Context, *TriggerRefreshRequest) (*TriggerRefreshResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerRefresh not implemented")
}
func (UnimplementedNomadBothererServer) GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedNomadBothererServer) mustEmbedUnimplementedNomadBothererServer() {}
func (UnimplementedNomadBothererServer) testEmbeddedByValue()                       {}

// UnsafeNomadBothererServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NomadBothererServer will
// result in compilation errors.
type UnsafeNomadBothererServer interface {
	mustEmbedUnimplementedNomadBothererServer()
}

func RegisterNomadBothererServer(s grpc.ServiceRegistrar, srv NomadBothererServer) {
	// If the following call panics, it indicates UnimplementedNomadBothererServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NomadBotherer_ServiceDesc, srv)
}

func _NomadBotherer_GetDiffs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiffsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NomadBothererServer).GetDiffs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NomadBotherer_GetDiffs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NomadBothererServer).GetDiffs(ctx, req.(*GetDiffsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NomadBotherer_GetSelectedJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSelectedJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NomadBothererServer).GetSelectedJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NomadBotherer_GetSelectedJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NomadBothererServer).GetSelectedJobs(ctx, req.(*GetSelectedJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NomadBotherer_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NomadBothererServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NomadBotherer_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NomadBothererServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NomadBotherer_TriggerRefresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerRefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NomadBothererServer).TriggerRefresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NomadBotherer_TriggerRefresh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NomadBothererServer).TriggerRefresh(ctx, req.(*TriggerRefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NomadBotherer_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NomadBothererServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NomadBotherer_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NomadBothererServer).GetVersion(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NomadBotherer_ServiceDesc is the grpc.ServiceDesc for NomadBotherer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NomadBotherer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nomad_botherer.v1.NomadBotherer",
	HandlerType: (*NomadBothererServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDiffs",
			Handler:    _NomadBotherer_GetDiffs_Handler,
		},
		{
			MethodName: "GetSelectedJobs",
			Handler:    _NomadBotherer_GetSelectedJobs_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _NomadBotherer_GetStatus_Handler,
		},
		{
			MethodName: "TriggerRefresh",
			Handler:    _NomadBotherer_TriggerRefresh_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _NomadBotherer_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nomad_botherer.proto",
}
