// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: nomad_botherer.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDiffsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiffsRequest) Reset() {
	*x = GetDiffsRequest{}
	mi := &file_nomad_botherer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiffsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiffsRequest) ProtoMessage() {}

func (x *GetDiffsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nomad_botherer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiffsRequest.ProtoReflect.Descriptor instead.
func (*GetDiffsRequest) Descriptor() ([]byte, []int) {
	return file_nomad_botherer_proto_rawDescGZIP(), []int{0}
}

type GetDiffsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Diffs []*JobDiff             `protobuf:"bytes,1,rep,name=diffs,proto3" json:"diffs,omitempty"`
	// RFC3339 timestamp of the last diff check.
	LastCheckTime string `protobuf:"bytes,2,opt,name=last_check_time,json=lastCheckTime,proto3" json:"last_check_time,omitempty"`
	// Git commit hash that was current during the last diff check.
	LastCommit    string `protobuf:"bytes,3,opt,name=last_commit,json=lastCommit,proto3" json:"last_commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiffsResponse) Reset() {
	*x = GetDiffsResponse{}
	mi := &file_nomad_botherer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiffsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiffsResponse) ProtoMessage() {}

func (x *GetDiffsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nomad_botherer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiffsResponse.ProtoReflect.Descriptor instead.
func (*GetDiffsResponse) Descriptor() ([]byte, []int) {
	return file_nomad_botherer_proto_rawDescGZIP(), []int{1}
}

func (x *GetDiffsResponse) GetDiffs() []*JobDiff {
	if x != nil {
		return x.Diffs
	}
	return nil
}

func (x *GetDiffsResponse) GetLastCheckTime() string {
	if x != nil {
		return x.LastCheckTime
	}
	return ""
}

func (x *GetDiffsResponse) GetLastCommit() string {
	if x != nil {
		return x.LastCommit
	}
	return ""
}

type JobDiff struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	JobId string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Path to the HCL file; empty when diff_type is missing_from_hcl.
	HclFile string `protobuf:"bytes,2,opt,name=hcl_file,json=hclFile,proto3" json:"hcl_file,omitempty"`
	// One of: modified, missing_from_nomad, missing_from_hcl.
	DiffType string `protobuf:"bytes,3,opt,name=diff_type,json=diffType,proto3" json:"diff_type,omitempty"`
	// Human-readable summary of the diff (nomad plan output excerpt).
	Detail        string `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobDiff) Reset() {
	*x = JobDiff{}
	mi := &file_nomad_botherer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobDiff) ProtoMessage() {}

func (x *JobDiff) ProtoReflect() protoreflect.Message {
	mi := &file_nomad_botherer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobDiff.ProtoReflect.Descriptor instead.
func (*JobDiff) Descriptor() ([]byte, []int) {
	return file_nomad_botherer_proto_rawDescGZIP(), []int{2}
}

func (x *JobDiff) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobDiff) GetHclFile() string {
	if x != nil {
		return x.HclFile
	}
	return ""
}

func (x *JobDiff) GetDiffType() string {
	if x != nil {
		return x.DiffType
	}
	return ""
}

func (x *JobDiff) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type GetSelectedJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSelectedJobsRequest) Reset() {
	*x = GetSelectedJobsRequest{}
	mi := &file_nomad_botherer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSelectedJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSelectedJobsRequest) ProtoMessage() {}

func (x *GetSelectedJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nomad_botherer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSelectedJobsRequest.ProtoReflect.Descriptor instead.
func (*GetSelectedJobsRequest) Descriptor() ([]byte, []int) {
	return file_nomad_botherer_proto_rawDescGZIP(), []int{3}
}

type GetSelectedJobsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Jobs  []*SelectedJob         `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	// RFC3339 timestamp of the last diff check.
	LastCheckTime string `protobuf:"bytes,2,opt,name=last_check_time,json=lastCheckTime,proto3" json:"last_check_time,omitempty"`
	// Git commit hash that was current during the last diff check.
	LastCommit    string `protobuf:"bytes,3,opt,name=last_commit,json=lastCommit,proto3" json:"last_commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSelectedJobsResponse) Reset() {
	*x = GetSelectedJobsResponse{}
	mi := &file_nomad_botherer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSelectedJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSelectedJobsResponse) ProtoMessage() {}

func (x *GetSelectedJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nomad_botherer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSelectedJobsResponse.ProtoReflect.Descriptor instead.
func (*GetSelectedJobsResponse) Descriptor() ([]byte, []int) {
	return file_nomad_botherer_proto_rawDescGZIP(), []int{4}
}

func (x *GetSelectedJobsResponse) GetJobs() []*SelectedJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *GetSelectedJobsResponse) GetLastCheckTime() string {
	if x != nil {
		return x.LastCheckTime
	}
	return ""
}

func (x *GetSelectedJobsResponse) GetLastCommit() string {
	if x != nil {
		return x.LastCommit
	}
	return ""
}

// SelectedJob records a job that matched the configured selection criteria.
type SelectedJob struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	JobId string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// One of: glob, meta, both.
	SelectionReason string `protobuf:"bytes,2,opt,name=selection_reason,json=selectionReason,proto3" json:"selection_reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SelectedJob) Reset() {
	*x = SelectedJob{}
	mi := &file_nomad_botherer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectedJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectedJob) ProtoMessage() {}

func (x *SelectedJob) ProtoReflect() protoreflect.Message {
	mi := &file_nomad_botherer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectedJob.ProtoReflect.Descriptor instead.
func (*SelectedJob) Descriptor() ([]byte, []int) {
	return file_nomad_botherer_proto_rawDescGZIP(), []int{5}
}

func (x *SelectedJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SelectedJob) GetSelectionReason() string {
	if x != nil {
		return x.SelectionReason
	}
	return ""
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_nomad_botherer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nomad_botherer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_nomad_botherer_proto_rawDescGZIP(), []int{6}
}

type GetStatusResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	LastCommit string                 `protobuf:"bytes,1,opt,name=last_commit,json=lastCommit,proto3" json:"last_commit,omitempty"`
	// RFC3339 timestamp of the last successful git fetch.
	LastUpdateTime string `protobuf:"bytes,2,opt,name=last_update_time,json=lastUpdateTime,proto3" json:"last_update_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_nomad_botherer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nomad_botherer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_nomad_botherer_proto_rawDescGZIP(), []int{7}
}

func (x *GetStatusResponse) GetLastCommit() string {
	if x != nil {
		return x.LastCommit
	}
	return ""
}

func (x *GetStatusResponse) GetLastUpdateTime() string {
	if x != nil {
		return x.LastUpdateTime
	}
	return ""
}

type TriggerRefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerRefreshRequest) Reset() {
	*x = TriggerRefreshRequest{}
	mi := &file_nomad_botherer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRefreshRequest) ProtoMessage() {}

func (x *TriggerRefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nomad_botherer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRefreshRequest.ProtoReflect.Descriptor instead.
func (*TriggerRefreshRequest) Descriptor() ([]byte, []int) {
	return file_nomad_botherer_proto_rawDescGZIP(), []int{8}
}

type TriggerRefreshResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerRefreshResponse) Reset() {
	*x = TriggerRefreshResponse{}
	mi := &file_nomad_botherer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRefreshResponse) ProtoMessage() {}

func (x *TriggerRefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nomad_botherer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRefreshResponse.ProtoReflect.Descriptor instead.
func (*TriggerRefreshResponse) Descriptor() ([]byte, []int) {
	return file_nomad_botherer_proto_rawDescGZIP(), []int{9}
}

func (x *TriggerRefreshResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_nomad_botherer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nomad_botherer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_nomad_botherer_proto_rawDescGZIP(), []int{10}
}

type GetVersionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Semver tag or "dev" when built without -ldflags.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Git commit hash at build time, or "unknown".
	Commit string `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	// RFC3339 build timestamp, or "unknown".
	BuildDate     string `protobuf:"bytes,3,opt,name=build_date,json=buildDate,proto3" json:"build_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_nomad_botherer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nomad_botherer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_nomad_botherer_proto_rawDescGZIP(), []int{11}
}

func (x *GetVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetVersionResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *GetVersionResponse) GetBuildDate() string {
	if x != nil {
		return x.BuildDate
	}
	return ""
}

var File_nomad_botherer_proto protoreflect.FileDescriptor

const file_nomad_botherer_proto_rawDesc = "" +
	"\n" +
	"\x14nomad_botherer.proto\x12\x11nomad_botherer.v1\"\x11\n" +
	"\x0fGetDiffsRequest\"\x8d\x01\n" +
	"\x10GetDiffsResponse\x120\n" +
	"\x05diffs\x18\x01 \x03(\v2\x1a.nomad_botherer.v1.JobDiffR\x05diffs\x12&\n" +
	"\x0flast_check_time\x18\x02 \x01(\tR\rlastCheckTime\x12\x1f\n" +
	"\vlast_commit\x18\x03 \x01(\tR\n" +
	"lastCommit\"p\n" +
	"\aJobDiff\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\bhcl_file\x18\x02 \x01(\tR\ahclFile\x12\x1b\n" +
	"\tdiff_type\x18\x03 \x01(\tR\bdiffType\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\"\x18\n" +
	"\x16GetSelectedJobsRequest\"\x96\x01\n" +
	"\x17GetSelectedJobsResponse\x122\n" +
	"\x04jobs\x18\x01 \x03(\v2\x1e.nomad_botherer.v1.SelectedJobR\x04jobs\x12&\n" +
	"\x0flast_check_time\x18\x02 \x01(\tR\rlastCheckTime\x12\x1f\n" +
	"\vlast_commit\x18\x03 \x01(\tR\n" +
	"lastCommit\"O\n" +
	"\vSelectedJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12)\n" +
	"\x10selection_reason\x18\x02 \x01(\tR\x0fselectionReason\"\x12\n" +
	"\x10GetStatusRequest\"^\n" +
	"\x11GetStatusResponse\x12\x1f\n" +
	"\vlast_commit\x18\x01 \x01(\tR\n" +
	"lastCommit\x12(\n" +
	"\x10last_update_time\x18\x02 \x01(\tR\x0elastUpdateTime\"\x17\n" +
	"\x15TriggerRefreshRequest\"2\n" +
	"\x16TriggerRefreshResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x13\n" +
	"\x11GetVersionRequest\"e\n" +
	"\x12GetVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\tR\x06commit\x12\x1d\n" +
	"\n" +
	"build_date\x18\x03 \x01(\tR\tbuildDate2\xe8\x03\n" +
	"\rNomadBotherer\x12S\n" +
	"\bGetDiffs\x12\".nomad_botherer.v1.GetDiffsRequest\x1a#.nomad_botherer.v1.GetDiffsResponse\x12h\n" +
	"\x0fGetSelectedJobs\x12).nomad_botherer.v1.GetSelectedJobsRequest\x1a*.nomad_botherer.v1.GetSelectedJobsResponse\x12V\n" +
	"\tGetStatus\x12#.nomad_botherer.v1.GetStatusRequest\x1a$.nomad_botherer.v1.GetStatusResponse\x12e\n" +
	"\x0eTriggerRefresh\x12(.nomad_botherer.v1.TriggerRefreshRequest\x1a).nomad_botherer.v1.TriggerRefreshResponse\x12Y\n" +
	"\n" +
	"GetVersion\x12$.nomad_botherer.v1.GetVersionRequest\x1a%.nomad_botherer.v1.GetVersionResponseB7Z5github.com/gerrowadat/nomad-botherer/internal/grpcapib\x06proto3"

var (
	file_nomad_botherer_proto_rawDescOnce sync.Once
	file_nomad_botherer_proto_rawDescData []byte
)

func file_nomad_botherer_proto_rawDescGZIP() []byte {
	file_nomad_botherer_proto_rawDescOnce.Do(func() {
		file_nomad_botherer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nomad_botherer_proto_rawDesc), len(file_nomad_botherer_proto_rawDesc)))
	})
	return file_nomad_botherer_proto_rawDescData
}

var file_nomad_botherer_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_nomad_botherer_proto_goTypes = []any{
	(*GetDiffsRequest)(nil),         // 0: nomad_botherer.v1.GetDiffsRequest
	(*GetDiffsResponse)(nil),        // 1: nomad_botherer.v1.GetDiffsResponse
	(*JobDiff)(nil),                 // 2: nomad_botherer.v1.JobDiff
	(*GetSelectedJobsRequest)(nil),  // 3: nomad_botherer.v1.GetSelectedJobsRequest
	(*GetSelectedJobsResponse)(nil), // 4: nomad_botherer.v1.GetSelectedJobsResponse
	(*SelectedJob)(nil),             // 5: nomad_botherer.v1.SelectedJob
	(*GetStatusRequest)(nil),        // 6: nomad_botherer.v1.GetStatusRequest
	(*GetStatusResponse)(nil),       // 7: nomad_botherer.v1.GetStatusResponse
	(*TriggerRefreshRequest)(nil),   // 8: nomad_botherer.v1.TriggerRefreshRequest
	(*TriggerRefreshResponse)(nil),  // 9: nomad_botherer.v1.TriggerRefreshResponse
	(*GetVersionRequest)(nil),       // 10: nomad_botherer.v1.GetVersionRequest
	(*GetVersionResponse)(nil),      // 11: nomad_botherer.v1.GetVersionResponse
}
var file_nomad_botherer_proto_depIdxs = []int32{
	2,  // 0: nomad_botherer.v1.GetDiffsResponse.diffs:type_name -> nomad_botherer.v1.JobDiff
	5,  // 1: nomad_botherer.v1.GetSelectedJobsResponse.jobs:type_name -> nomad_botherer.v1.SelectedJob
	0,  // 2: nomad_botherer.v1.NomadBotherer.GetDiffs:input_type -> nomad_botherer.v1.GetDiffsRequest
	3,  // 3: nomad_botherer.v1.NomadBotherer.GetSelectedJobs:input_type -> nomad_botherer.v1.GetSelectedJobsRequest
	6,  // 4: nomad_botherer.v1.NomadBotherer.GetStatus:input_type -> nomad_botherer.v1.GetStatusRequest
	8,  // 5: nomad_botherer.v1.NomadBotherer.TriggerRefresh:input_type -> nomad_botherer.v1.TriggerRefreshRequest
	10, // 6: nomad_botherer.v1.NomadBotherer.GetVersion:input_type -> nomad_botherer.v1.GetVersionRequest
	1,  // 7: nomad_botherer.v1.NomadBotherer.GetDiffs:output_type -> nomad_botherer.v1.GetDiffsResponse
	4,  // 8: nomad_botherer.v1.NomadBotherer.GetSelectedJobs:output_type -> nomad_botherer.v1.GetSelectedJobsResponse
	7,  // 9: nomad_botherer.v1.NomadBotherer.GetStatus:output_type -> nomad_botherer.v1.GetStatusResponse
	9,  // 10: nomad_botherer.v1.NomadBotherer.TriggerRefresh:output_type -> nomad_botherer.v1.TriggerRefreshResponse
	11, // 11: nomad_botherer.v1.NomadBotherer.GetVersion:output_type -> nomad_botherer.v1.GetVersionResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_nomad_botherer_proto_init() }
func file_nomad_botherer_proto_init() {
	if File_nomad_botherer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nomad_botherer_proto_rawDesc), len(file_nomad_botherer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nomad_botherer_proto_goTypes,
		DependencyIndexes: file_nomad_botherer_proto_depIdxs,
		MessageInfos:      file_nomad_botherer_proto_msgTypes,
	}.Build()
	File_nomad_botherer_proto = out.File
	file_nomad_botherer_proto_goTypes = nil
	file_nomad_botherer_proto_depIdxs = nil
}
